### ISSUE TITLE
macplus-system.zip won't seem to uncompress

### ISSUE THREAD

**Issue by verticalgrain** [jsdf/pce#12]
When I attempt to unzip macplus-system.zip, it uncompresses to a .cpgz, which uncompresses to a .zip, which uncompresses to a .cpgz, and it keeps going like that.

**Comment by jsdf** [comment]
looks like the http -> https redirect was messing things up. can you give it another try now?

**Comment by verticalgrain** [comment]
You were right, it unzips properly now. 

Thanks very much for your help!

Jamie
