### ISSUE TITLE
Google Analistics

### ISSUE THREAD

**Issue by ghost** [jsdf/pce#22]
Remove GA Or I Will Stop Using This

**Comment by ghost** [comment]
WTF?

**Comment by ghost** [comment]
Just please remove ’Google Analytics’ From PCE

**Comment by ghost** [comment]
Just so everybuddy knows it is 22:13 where i live. I live in Stockholm

**Comment by ghost** [comment]
Install [this extension](https://duckduckgo.com/app). And [this one](https://ublockorigin.com/), if you want to.

**Comment by ghost** [comment]
But... _seriously?_

**Comment by jsdf** [comment]
there’s no google analytics code in this repo. i use analytics on my website to better understand what content people find most valuable.  you’re free to host pce-js in your own website if you wish.
